+ This cleans up the makefiles and includes the new configure script from the oscar framework.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16,6 +16,8 @@
 # with this library; if not, write to the Free Software Foundation, Inc., 51
 # Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 
+set -e -o pipefail
+
 print() { echo "$1" >&2; }
 inform() { print "$0: $1"; }
 warn() { print "Warning: $1"; }
@@ -23,53 +25,13 @@ error() { inform "Error: $1"; }
 fail() { error "$1"; exit 1; }
 status() { echo -n "$1" >&2; }
 
-trim() {
-	# trim $1: cut of leading and trailing white space
-	# $1: the string to trim
-	
-	echo $1
-}
-
-get_config_index() {
-	# get_config_index: $1: Get the index of a configuration variable name in the CONFIG_NAMES array.
-	# $1: Name of the configuration variable.
-	
-	local NAME=$1
-	
-	for i in ${!CONFIG_NAMES[*]}; do
-		[ "${CONFIG_NAMES[$i]}" == "$NAME" ] && echo $i && return 0
-	done
-	
-	return 1
-}
-
 get_config() {
 	# get_config $1 $2: load a configuration from a configuration file
 	# $1: the name of the configuration file
 	# $2: name of the configuration variable
 	
-	local CONFIG_FILE=$1 NAME=$2
-	
-	local VALUE
-	
-	[ -e "$CONFIG_FILE" ] && VALUE=$(trim "$(grep -E "^$NAME" < $CONFIG_FILE | cut -d "=" -f 2)")
-	[ $VALUE ] || VALUE=${CONFIG_DFAULTS["$(get_config_index "$NAME")"]}
-	
-	echo "$VALUE"
-}
-
-read_config() {
-	# read_config $1: read settings from a configuration file
-	# $1: name of the configuration file
-	
-	local NAME VALUE
-	
-	cat "$1" | while read i; do
-		NAME=$(trim $(echo $i | cut -d "=" -f 1))
-		VALUE=$(trim $(echo $i | cut -d "=" -f 2))
-		
-		eval $NAME="$VALUE"
-	done
+	local CONFIG_FILE=$1 NAME=$2 EXPR="s/^#?$NAME[\t ]*=[\t ]*(.*)[\t ]*$/\1/p"
+	[ -e "$CONFIG_FILE" ] && sed -rn "$EXPR" < "$CONFIG_FILE" | head -n 1 || true
 }
 
 ask() {
@@ -81,90 +43,84 @@ ask() {
 	[ "$REPLY" ] && echo $REPLY || echo $1
 }
 
-enable_match() {
-	# enable_match $1 $2: return true if the contents of the configuration variable $1 are matched by the regex $2.
-	# $1: The name of the variable
-	# $2: Regex the variable has to match with grep -xE
+variable_read() {
+	# variable_read $1: read the value of the variable with the given name
+	# $1: the name of the variable
 	
-	local NAME=$1 EXPR=$2
-	
-	echo "${CONFIG_VALUES["$(get_config_index "$NAME")"]}" | grep -xqE "$EXPR" && return 0 || return 1
+	eval echo \"\$"$1"\"
 }
 
-# Configuration Parameters
-# Each of the arrays has the same length and contain at the same index information for one configuration variable. It's a mess, I know.
-
-# Name of the configuration file relative to this script
-CONFIG_FILE=".config"
-# Names of the confguration variables as they can be accessed from a Makefile
-CONFIG_NAMES=(CONFIG_PRIVATE_FRAMEWORK CONFIG_FRAMEWORK_PATH CONFIG_TARGET_IP)
-# Prompts displayed when asking for a configuration
-CONFIG_PROMPTS=("Is the Oscar Framework already in the folder ./oscar? (y/n)" "Enter the path to the Oscar Framework." "Enter the IP Address of the target device")
-# Functions to run to find out whether a configuration will be asked for. The empty string is equivalent to "true" (always ask).
-CONFIG_ENABLE=('' 'enable_match CONFIG_PRIVATE_FRAMEWORK n' '')
-# Regular expressions to match an answer to with grep -xE to find out whether an answer is valid. The empty string is equivalent to ".*" (everything goes).
-CONFIG_CHECK=('y|n' '.+' '[0-9a-zA-Z.:-]*')
-# Default answers to new questions.
-CONFIG_DFAULTS=("n" "../oscar" "192.168.1.10")
+variable_write() {
+	# variable_write $1 $2: write a value to the variable with the given name
+	# $1: the name of the variable
+	# $2: the value to write
+	
+	eval "$1"='$2'
+}
 
 SCRIPT_DIR=$(dirname "$BASH_SOURCE")
-CONFIG_FILE_PATH=$(readlink -f "$SCRIPT_DIR/$CONFIG_FILE")
+CONF_FILE=$(readlink -f "$SCRIPT_DIR/.config")
 
-# Read the configurations set on the command line
+. "$SCRIPT_DIR/configure.in"
+
+# Read the configurations set on the command line.
 while [ "$1" ]; do
+	echo "$1" | grep -qF "=" || "Unknown option: $$1"
+	
 	NAME=$(echo "$1" | cut -d "=" -f 1)
 	VALUE=$(echo "$1" | cut -d "=" -f 2)
-	INDEX=$(get_config_index "$NAME")
 	
-	[ "$INDEX" ] && CONFIG_VALUES[$INDEX]=$VALUE || fail "Unknown option: $NAME"
+	echo "$NAME" | grep -xqF "$(echo "$CONFIGS" | tr ' ' '\n' | sed -r 's/^/CONFIG_/')" || fail "Unknown variable: $$NAME"
+	variable_write "$NAME" "$VALUE"
 	
 	shift
 done
 
-# ask the user about configurations
-for i in ${!CONFIG_NAMES[*]}; do
-	NAME=${CONFIG_NAMES[$i]}
+# Ask the user about configurations.
+for i_name in $CONFIGS; do
+	NAME="CONFIG_$i_name"
 	
-	# Check if the variable was set on the command line.
-	if ! [ "${CONFIG_VALUES[$i]}" ]; then
-		# Check wether the configuration should be asked.
-		
-		DO_NOT_ASK=
-		if [ "${CONFIG_ENABLE[$i]}" ]; then
-			${CONFIG_ENABLE[$i]} || DO_NOT_ASK=1
-		fi
-		
-		if [ "$DO_NOT_ASK" ]; then
-			CONFIG_NAMES[$i]=
+	{
+		VALUE_CLI=$(variable_read "$NAME")
+		VALUE_FILE=$(get_config "$CONF_FILE" "$NAME")
+		VALUE_DEFAULT=$("$NAME" default)
+	} > /dev/null
+	
+	# Check if we should ask for the configuration.
+	if "$NAME" enabled; then
+		# Check if the configuration value has been given on the command line.
+		if [ "$VALUE_CLI" ]; then
+			VALUE_NEW=$VALUE_CLI
 		else
-			VALUE=$(get_config $CONFIG_FILE_PATH $NAME)
-			PROMPT=${CONFIG_PROMPTS[$i]}
+			[ "$VALUE_FILE" ] && VALUE=$VALUE_FILE || VALUE=$VALUE_DEFAULT
+			PROMPT=$("$NAME" prompt)
 			
 			while true; do
 				VALUE_NEW=$(ask "$VALUE" "$PROMPT")
 				
-				if [ "${CONFIG_CHECK[$i]}" ]; then
-					echo "$VALUE_NEW" | grep -xqE "${CONFIG_CHECK[$i]}" && break
-					
-					print "The configuration is not valid: $VALUE_NEW"
-				else
-					break
-				fi
+				echo "$VALUE_NEW" | "$NAME" check && break
+				print "The configuration is not valid: $VALUE_NEW"
 			done
 			
-			CONFIG_VALUES[$i]=$VALUE_NEW
-		fi
+		fi > /dev/null
+		
+		variable_write "$NAME" "$VALUE_NEW" > /dev/null
+		echo "$NAME = $VALUE_NEW"
+	else
+		if [ "$VALUE_CLI" ]; then
+			VALUE_NEW=$VALUE_CLI
+		elif [ "$VALUE_FILE" ]; then
+			VALUE_NEW=$VALUE_FILE
+		else
+			VALUE_NEW=
+		fi > /dev/null
+		
+		[ "$VALUE_NEW" ] && echo "#$NAME = $VALUE_NEW"
 	fi
-done
+done > "${CONF_FILE}~"
 
-# write the configuration file
-rm -f "${CONFIG_FILE_PATH}~"
-for i in ${!CONFIG_NAMES[*]}; do
-	NAME=${CONFIG_NAMES[$i]}
-	VALUE=${CONFIG_VALUES[$i]}
-	
-	[ "$NAME" ] && echo "$NAME = $VALUE" >> "${CONFIG_FILE_PATH}~"
-done
-mv -f "${CONFIG_FILE_PATH}~" "${CONFIG_FILE_PATH}"
+# Move the new configuration file in place.
+mv -f "${CONF_FILE}~" "${CONF_FILE}"
 
+# Call the makefile to update according to the new configuration.
 make -C "$SCRIPT_DIR" --no-print-directory reconfigure
